"""Create Bid tables

Revision ID: 039bb2631d24
Revises: dd69c535eb08
Create Date: 2024-09-13 21:37:41.465329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '039bb2631d24'
down_revision: Union[str, None] = 'dd69c535eb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', postgresql.ENUM('CREATED', 'PUBLISHED', 'CLOSED', name='statustype'), nullable=False),
    sa.Column('decision', postgresql.ENUM('REVIEW', 'APPROVED', 'REJECTED', name='decisiontype'), nullable=False),
    sa.Column('tenderId', sa.UUID(), nullable=False),
    sa.Column('authorType', postgresql.ENUM('ORGANIZATION', 'USER', name='authortype'), nullable=False),
    sa.Column('authorId', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenderId'], ['tender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bid')
    # ### end Alembic commands ###
